name: sql_avance

services:
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdb:/var/lib/postgresql
      - ./scripts_init:/docker-entrypoint-initdb.d
    networks:
      - pgdb_network

  pgadmin:
    depends_on:
      - pgdb
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./storage_pgadmin:/var/lib/pgadmin/storage
    networks:
      - pgdb_network

volumes:
  pgdb:
  pgadmin:

networks:
  pgdb_network: